# Data 

### Data intake, formatting, and cleaning

```
"if i could open my arms
and span the length of the isle of manhattan
id bring it to where you are
making a lake of the east river and hudson" - death cab for cutie
```

In [1]:
source("src/functions_and_things.r")

load_libraries()

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ lubridate 1.9.4     ✔ tibble    3.3.0
✔ purrr     1.1.0     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer


Warning message:
“package ‘zoo’ was built under R version 4.5.2”

Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

## Pre polic data

June 1, 2024-December 31, 2024

* `subway_pre_df_jun` - June 1, 2024 - July 31, 2024
* `subway_pre_df_aug` - August 1, 2024 - September 31, 2024
* `subway_pre_df_oct` - October 1, 2024 - December 31, 2024

In [2]:
subway_pre_df_jun = read.csv("/Users/Local/statsproject/data/ignore/MTA_Jun2024_Subway_Hourly.csv")

subway_pre_df_aug = read.csv("/Users/Local/statsproject/data/ignore/MTA_Aug2024_Subway_Hourly.csv")

subway_pre_df_oct = read.csv("/Users/Local/statsproject/data/ignore/MTA_Oct2024_Subway_Hourly.csv")
subway_pre_df_oct |> select(-transfers) -> subway_pre_df_oct

In [3]:
subway_pre_df = rbind(subway_pre_df_oct, 
                      subway_pre_df_aug, 
                      subway_pre_df_jun)

subway_pre_df$time = 0

head(subway_pre_df)

  transit_timestamp      transit_mode station_complex_id station_complex
1 01/01/2025 12:00:00 AM subway       122                Graham Av (L)
2 01/01/2025 12:00:00 AM subway       169                Canal St (A,C,E)
3 01/01/2025 12:00:00 AM subway       173                High St (A,C)
4 01/01/2025 12:00:00 AM subway       292                Fulton St (G)
5 01/01/2025 12:00:00 AM subway       377                3 Av-138 St (6)
6 01/01/2025 12:00:00 AM subway       384                Burnside Av (4)
  borough   payment_method fare_class_category   ridership latitude longitude
1 Brooklyn  metrocard      Metrocard - Full Fare 8         40.71457 -73.94405
2 Manhattan omny           OMNY - Full Fare      171       40.72082 -74.00523
3 Brooklyn  metrocard      Metrocard - Full Fare 59        40.69934 -73.99053
4 Brooklyn  omny           OMNY - Other          5         40.68712 -73.97537
5 Bronx     metrocard      Metrocard - Fair Fare 2         40.81047 -73.92614
6 Bronx     omny           OMNY - Full Fare      12        40.85345 -73.90768
  time
1 0
2 0
3 0
4 0
5 0
6 0

In [4]:
head(subway_pre_df)

  transit_timestamp      transit_mode station_complex_id station_complex
1 01/01/2025 12:00:00 AM subway       122                Graham Av (L)
2 01/01/2025 12:00:00 AM subway       169                Canal St (A,C,E)
3 01/01/2025 12:00:00 AM subway       173                High St (A,C)
4 01/01/2025 12:00:00 AM subway       292                Fulton St (G)
5 01/01/2025 12:00:00 AM subway       377                3 Av-138 St (6)
6 01/01/2025 12:00:00 AM subway       384                Burnside Av (4)
  borough   payment_method fare_class_category   ridership latitude longitude
1 Brooklyn  metrocard      Metrocard - Full Fare 8         40.71457 -73.94405
2 Manhattan omny           OMNY - Full Fare      171       40.72082 -74.00523
3 Brooklyn  metrocard      Metrocard - Full Fare 59        40.69934 -73.99053
4 Brooklyn  omny           OMNY - Other          5         40.68712 -73.97537
5 Bronx     metrocard      Metrocard - Fair Fare 2         40.81047 -73.92614
6 Bronx     omny           OMNY - Full Fare      12        40.85345 -73.90768
  time
1 0
2 0
3 0
4 0
5 0
6 0

## Post policy data

January 1, 2025 - June 1st, 2025

In [5]:
subway_post_df = read.csv("/Users/Local/statsproject/data/ignore/MTA_Jan2025_Subway_Hourly.csv")
subway_post_df$time = 1

head(subway_post_df)

  transit_timestamp      transit_mode station_complex_id
1 10/01/2024 12:00:00 AM subway       69
2 10/01/2024 12:00:00 AM subway       422
3 10/01/2024 12:00:00 AM subway       602
4 10/01/2024 12:00:00 AM subway       397
5 10/01/2024 12:00:00 AM subway       65
6 10/01/2024 12:00:00 AM subway       405
  station_complex                  borough   payment_method
1 25 Av (D)                        Brooklyn  omny
2 Burke Av (2,5)                   Bronx     metrocard
3 14 St-Union Sq (L,N,Q,R,W,4,5,6) Manhattan metrocard
4 86 St (4,5,6)                    Manhattan metrocard
5 79 St (D)                        Brooklyn  metrocard
6 23 St (6)                        Manhattan metrocard
  fare_class_category         ridership latitude longitude time
1 OMNY - Other                1         40.59771 -73.98683 1
2 Metrocard - Unlimited 7-Day 1         40.87136 -73.86716 1
3 Metrocard - Fair Fare       25        40.73574 -73.98995 1
4 Metrocard - Other           8         40.77949 -73.95559 1
5 Metrocard - Unlimited 7-Day 1         40.61350 -74.00061 1
6 Metrocard - Unlimited 7-Day 7         40.73986 -73.98660 1

## Stacking pre and post datasets

June 2024 - June 2025

24 million rows

In [6]:
df <- rbind(subway_pre_df, subway_post_df)

nrow(df)

[1] 24456218

## CBD Boolean

By latitude/ longitude

<img src="/Users/Local/statsproject/pics/cbd_subway_coordbox.jpg" width="400" height="400">

In [7]:
lat_high = 40.771372
long_high= -74.00782 

lat_low = 40.696999
long_low = -73.966776

In [8]:
df$coords_cbd <- with(df, 
    latitude >= lat_low & latitude <= lat_high & 
    longitude <= long_low & longitude >= long_high)

Was the subway encoding close to the box one?

In [9]:
sum(df$coords_cbd == TRUE)

[1] 3660800

In [10]:
sum(is.na(df$ridership))

df <- drop_na(df, ridership)

[1] 0

## Aggregate dataset

In [11]:
df$ridership = as.integer(df$ridership)

str(df)

Warning message:
“NAs introduced by coercion”

'data.frame':	24456218 obs. of  12 variables:
 $ transit_timestamp  : chr  "01/01/2025 12:00:00 AM" "01/01/2025 12:00:00 AM" "01/01/2025 12:00:00 AM" "01/01/2025 12:00:00 AM" ...
 $ transit_mode       : chr  "subway" "subway" "subway" "subway" ...
 $ station_complex_id : chr  "122" "169" "173" "292" ...
 $ station_complex    : chr  "Graham Av (L)" "Canal St (A,C,E)" "High St (A,C)" "Fulton St (G)" ...
 $ borough            : chr  "Brooklyn" "Manhattan" "Brooklyn" "Brooklyn" ...
 $ payment_method     : chr  "metrocard" "omny" "metrocard" "omny" ...
 $ fare_class_category: chr  "Metrocard - Full Fare" "OMNY - Full Fare" "Metrocard - Full Fare" "OMNY - Other" ...
 $ ridership          : int  8 171 59 5 2 12 1 98 2 2 ...
 $ latitude           : num  40.7 40.7 40.7 40.7 40.8 ...
 $ longitude          : num  -73.9 -74 -74 -74 -73.9 ...
 $ time               : num  0 0 0 0 0 0 0 0 0 0 ...
 $ coords_cbd         : logi  FALSE TRUE TRUE FALSE FALSE FALSE ...

In [12]:
df <- distinct(df) # remove duplicates in case i messed dates up

df |> 
    mutate(
        date = as.Date(mdy_hms(transit_timestamp))) |>
    group_by(
        date, borough, coords_cbd) |> 
    summarise(
        ridership = sum(ridership, na.rm = TRUE),
        .groups = "drop") |>
    select(date, borough, coords_cbd, ridership) -> df_daily

In [13]:
head(df_daily, 8)

  date       borough   coords_cbd ridership
1 2024-06-01 Bronx     FALSE      140211
2 2024-06-01 Brooklyn  FALSE      501778
3 2024-06-01 Brooklyn   TRUE       20848
4 2024-06-01 Manhattan FALSE      383193
5 2024-06-01 Manhattan  TRUE      575531
6 2024-06-01 Queens    FALSE      345374
7 2024-06-02 Bronx     FALSE      107377
8 2024-06-02 Brooklyn  FALSE      403802

## Checks

In [14]:
nrow(df_daily)

[1] 2196

In [15]:
n_distinct(df_daily$date)

[1] 366

In [16]:
write.csv(df_daily, "data/daily_ridership.csv", row.names = FALSE)

## Weather Data

Weather data from JFK International Airport reported on NOAA

Unit: Daily

https://www.ncdc.noaa.gov/cdo-web/

In [17]:
weather_df <- read.csv("data/weather.csv")

weather_df |> 
    rename(
        min_temp = TMIN, 
        snow = SNWD,
        rain = PRCP) |> 
    mutate(date = as.Date(DATE), format = "%m-%d-%Y") |> 
    select(date, min_temp, snow, rain) -> weather_df

head(weather_df)

  date       min_temp snow rain
1 2024-06-01 62       0    0.00
2 2024-06-02 62       0    0.00
3 2024-06-03 66       0    0.02
4 2024-06-04 64       0    0.00
5 2024-06-05 63       0    0.04
6 2024-06-06 69       0    0.58

In [18]:
df_merged <- df_daily |> left_join(weather_df, by = "date")

In [19]:
nrow(df_merged) == nrow(df_daily)

[1] TRUE

In [20]:
head(df_merged, 10)

   date       borough   coords_cbd ridership min_temp snow rain
1  2024-06-01 Bronx     FALSE      140211    62       0    0
2  2024-06-01 Brooklyn  FALSE      501778    62       0    0
3  2024-06-01 Brooklyn   TRUE       20848    62       0    0
4  2024-06-01 Manhattan FALSE      383193    62       0    0
5  2024-06-01 Manhattan  TRUE      575531    62       0    0
6  2024-06-01 Queens    FALSE      345374    62       0    0
7  2024-06-02 Bronx     FALSE      107377    62       0    0
8  2024-06-02 Brooklyn  FALSE      403802    62       0    0
9  2024-06-02 Brooklyn   TRUE       16680    62       0    0
10 2024-06-02 Manhattan FALSE      318951    62       0    0

## Economic Data

Unemployment rate data from NYC / Neward from FRED 

Unit: Monthly

https://fred.stlouisfed.org/series/NEWY636URN#

In [21]:
econ_df <- read.csv("/Users/Local/statsproject/data/NEWY636URN.csv")

econ_df |> 
    mutate(month = as.Date(observation_date, format = "%Y-%m-%d"),
           unemp = NEWY636URN) |> 
    select(month, unemp) -> econ_df

head(econ_df)

  month      unemp
1 2024-06-01 4.7
2 2024-07-01 5.2
3 2024-08-01 5.1
4 2024-09-01 4.3
5 2024-10-01 4.5
6 2024-11-01 4.5

In [22]:
df_merged |> mutate(month = floor_date(date, "month")) -> df_merged

In [23]:
class(df_merged$month) 
class(econ_df$month)

[1] "Date"

[1] "Date"

In [24]:
df_merged <- df_merged |> left_join(econ_df, by = "month")

head(df_merged)

  date       borough   coords_cbd ridership min_temp snow rain month      unemp
1 2024-06-01 Bronx     FALSE      140211    62       0    0    2024-06-01 4.7
2 2024-06-01 Brooklyn  FALSE      501778    62       0    0    2024-06-01 4.7
3 2024-06-01 Brooklyn   TRUE       20848    62       0    0    2024-06-01 4.7
4 2024-06-01 Manhattan FALSE      383193    62       0    0    2024-06-01 4.7
5 2024-06-01 Manhattan  TRUE      575531    62       0    0    2024-06-01 4.7
6 2024-06-01 Queens    FALSE      345374    62       0    0    2024-06-01 4.7

In [25]:
sum(is.na(df_merged$unemp))

[1] 0

In [26]:
write.csv(df_merged, "data/combined_data_daily.csv", row.names = FALSE)

## Weekly aggregation

Mostly for noise reduction in the plots and stuff

In [30]:
df_merged |> 
    mutate(week = floor_date(date, "week")) |>
    group_by(week, borough) |> 
    summarise(ridership = sum(ridership, na.rm = TRUE),
              min_temp = mean(min_temp, na.rm = TRUE),
              rain = sum(rain, na.rm = TRUE),
              snow = sum(snow, na.rm = TRUE),.groups = "drop") -> df_weekly

In [28]:
head(df_weekly)

  week       coords_cbd ridership min_temp rain snow
1 2024-05-26 FALSE       1370556  62.00000 0.00 0
2 2024-05-26  TRUE        596379  62.00000 0.00 0
3 2024-06-02 FALSE      12241159  65.14286 2.56 0
4 2024-06-02  TRUE       5003047  65.14286 1.28 0
5 2024-06-09 FALSE      12123413  63.42857 3.40 0
6 2024-06-09  TRUE       4968744  63.42857 1.70 0

In [31]:
write.csv(df_weekly, "data/combined_data_weekly.csv", row.names = FALSE)